baseURL = "/"
languageCode = "en-us"

title = "Siva Chegondi"
theme = "m10c"
disqusShortname="jokrhat"

paginate = 7

[params]
	author = "Siva Chegondi"
	description = "Full Stack developer with good knowledge of operations & cloud technologies"
    
    [params.style]
        darkestColor = "#e0e0e0"
        darkColor = "#ffffff"
        lightColor = "#474747"
        lightestColor = "#787878"
        primaryColor = "#1278c8"
	[[params.social]]
		name = "github"
		url = "https:///github.com/siva-chegondi"
	[[params.social]]
		name = "linkedin"
		url = "https://linkedin.com/in/siva-chegondi"

