baseURL = "https://jokrhat.in"
languageCode = "en-us"

title = "Jokrhat"
theme = "m10c"
disqusShortname="jokrhat"

paginate = 7

[params]
	author = "Siva Chegondi"
	description = "Web Engineer with good knowledge of *nix and DevOps"
    
    [params.style]
        darkestColor = "#e0e0e0"
        darkColor = "#ffffff"
        lightColor = "#474747"
        lightestColor = "#787878"
        primaryColor = "#1078c8"
	[[params.social]]
		name = "github"
		url = "https:///github.com/siva-chegondi"
	[[params.social]]
		name = "linkedin"
		url = "https://linkedin.com/in/siva-chegondi"

