baseURL = "https://jokrhat.in"
languageCode = "en-us"

title = "Jokrhat"
theme = "m10c"
disqusShortname="jokrhat"

paginate = 7

[params]
	author = "Siva Chegondi"
	description = "Web Engineer with good knowledge of *nix and DevOps"

	[[params.social]]
		name = "github"
		url = "https:///github.com/siva-chegondi"
	[[params.social]]
		name = "linkedin"
		url = "https://linkedin.com/in/siva-chegondi"

